[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"


[profile.release]
lto = "fat"
panic = "abort"
debug = true

[dependencies]
lazy_static = "1.4.0"
memmap2 = "0.9.4"
rustc-hash = "1.1.0"

[dev-dependencies]
pretty_assertions = "1.4.0"

[features]
single_thread = []
multi_thread = []
